import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

test("los destinos de widget usan R2 con control de concurrencia y proveedor Bearer", () => {
  const manifest = readFileSync(new URL("../lib/inscreen-widget-targets.ts", import.meta.url), "utf8")
  const publishRoute = readFileSync(new URL("../app/api/inscreen/widget-targets/route.ts", import.meta.url), "utf8")
  const providerRoute = readFileSync(new URL("../app/api/inscreen/provider/widget-targets/route.ts", import.meta.url), "utf8")
  assert.match(manifest, /widget-targets-v1\.json/)
  assert.match(manifest, /ifMatch|ifNoneMatch/)
  assert.match(manifest, /isR2PreconditionFailedError/)
  assert.match(publishRoute, /requireAuthSession/)
  assert.match(publishRoute, /withInscreenUserConfig/)
  assert.match(publishRoute, /export async function GET/)
  assert.match(publishRoute, /resolveInscreenWidgetTarget/)
  assert.match(providerRoute, /authorizeProviderToken/)
  assert.doesNotMatch(providerRoute, /token.*searchParams/i)
})

test("Drive separa fijos, crea shortcuts y publica solo carpetas sincronizadas no fijas", () => {
  const drive = readFileSync(new URL("../lib/google-drive.ts", import.meta.url), "utf8")
  const workspace = readFileSync(new URL("../lib/local-workspace-data.ts", import.meta.url), "utf8")
  assert.match(drive, /application\/vnd\.google-apps\.shortcut/)
  assert.match(drive, /name: "Fijos"/)
  assert.match(workspace, /pathVersion: 2/)
  assert.match(workspace, /status === "synced" && !item\.isPinned/)
  assert.match(workspace, /subjectId: location\.subjectId/)
  assert.match(workspace, /resolveLocalLogicalSubjectId\(item\.subjectId\)/)
  assert.match(workspace, /normalizeLocalWidgetTargetSyncItems/)
  assert.match(workspace, /published\?\.targetSignatures/)
  assert.match(workspace, /getWidgetTargetSignature/)
  assert.match(workspace, /processLocalWidgetTargetSyncQueue/)
  assert.match(workspace, /readCurrentLocalWidgetCatalog/)
  assert.match(workspace, /\{ subjects: publishedCatalog, target: current\.target \}/)
  assert.match(workspace, /catalogSignature: JSON\.stringify\(publishedCatalog\)/)
  assert.match(workspace, /No se pudo verificar el destino publicado/)
  assert.match(workspace, /actualUrl !== current\.target\.url/)
  assert.match(workspace, /lastPublishedAt/)
})

test("Drive e InScreen trabajan por eventos y el barrido completo queda manual", () => {
  const provider = readFileSync(new URL("../components/local-workspace-provider.tsx", import.meta.url), "utf8")
  const interceptor = readFileSync(new URL("../components/local-fetch-interceptor.tsx", import.meta.url), "utf8")
  const workspace = readFileSync(new URL("../lib/local-workspace-data.ts", import.meta.url), "utf8")
  assert.doesNotMatch(provider, /setInterval\([^)]*processLocal(?:Drive|Widget)SyncQueue/s)
  assert.doesNotMatch(provider.slice(provider.indexOf("const run = async () =>"), provider.indexOf("const reselectWorkspace")), /enqueueAllLocalMaterialsForDrive/)
  assert.match(provider, /await enqueueAllLocalMaterialsForDrive\(\)[\s\S]*await refreshAllLocalMaterialWidgetTargets\(\)/)
  assert.match(interceptor, /hasName \|\| hasPinned[\s\S]*processLocalDriveSyncQueue/)
  assert.match(interceptor, /body\?\.containerId !== undefined \|\| body\?\.materialType !== undefined[\s\S]*processLocalDriveSyncQueue/)
  assert.match(workspace, /entry\.item\.status !== "synced"\)\) continue/)
  assert.match(workspace, /widgetTargetSyncRequested = true[\s\S]*return processLocalWidgetTargetSyncQueue\(\)/)
  assert.match(workspace, /driveSyncRequested = true[\s\S]*return processLocalDriveSyncQueue\(\)/)
  assert.match(workspace, /cursado2026-widget-target-sync/)
  assert.match(provider, /Reintentar widgets/)
  assert.match(provider, /R2 revision/)
  assert.match(readFileSync(new URL("../components/subject-wheel.tsx", import.meta.url), "utf8"), /Enlace guardado localmente; pendiente para la APK/)
})

test("User.Services migra los sobres antiguos y OAuth devuelve un token completo", () => {
  const provider = readFileSync(new URL("../components/local-workspace-provider.tsx", import.meta.url), "utf8")
  const oauth = readFileSync(new URL("../app/api/google/oauth/callback/route.ts", import.meta.url), "utf8")
  const migration = readFileSync(new URL("../app/api/google/drive/migrate/route.ts", import.meta.url), "utf8")
  assert.match(provider, /loadInscreenFileHalf/)
  assert.match(provider, /loadDriveFileHalf/)
  assert.match(provider, /removeLegacyServiceFiles/)
  assert.match(oauth, /driveToken/)
  assert.doesNotMatch(oauth, /driveConfigCookie/)
  assert.match(migration, /readLegacyDriveUserConfig/)
})
