import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

function source(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8")
}

test("la migracion conserva materiales y hace idempotentes las asignaciones", () => {
  const migration = source("scripts/029-create-material-tags.sql")
  assert.match(migration, /REFERENCES subject_day_materials\(id\) ON DELETE CASCADE/)
  assert.match(migration, /PRIMARY KEY \(material_id, tag_id\)/)
  assert.doesNotMatch(migration, /(?:UPDATE|DELETE FROM) subject_day_materials/i)
})

test("el modo local cubre catalogo, asignacion y consulta por material", () => {
  const interceptor = source("components/local-fetch-interceptor.tsx")
  assert.match(interceptor, /listLocalMaterialTagWorkspace/)
  assert.match(interceptor, /assignLocalTagToMaterial/)
  assert.match(interceptor, /unassignLocalTagFromMaterial/)
  assert.match(interceptor, /listLocalTagsForMaterial/)
})

test("la lista de materiales permite filtrar, asignar tags y mover PDFs entre contenedores", () => {
  const subjectWheel = source("components/subject-wheel.tsx")
  const tagBar = source("components/material-tag-bar.tsx")
  assert.match(subjectWheel, /materialMatchesTagFilter/)
  assert.match(subjectWheel, /getData\("application\/x-study-tag-id"\)/)
  assert.match(tagBar, /setData\("application\/x-study-tag-id"/)
  assert.match(subjectWheel, /setData\("application\/x-study-material-id"/)
  assert.match(subjectWheel, /moveMaterialToContainer/)
  assert.match(subjectWheel, /draggedMaterialIdValue && Number\.isInteger\(draggedMaterialId\)/)
  assert.match(subjectWheel, /!tagIdValue \|\| !Number\.isInteger\(tagId\)/)
  assert.match(subjectWheel, /dataTransferHasPlainText/)
  assert.match(subjectWheel, /getData\("text\/plain"\)/)
  assert.match(subjectWheel, /createPdfFileFromText/)
  assert.match(subjectWheel, /text\/uri-list/)
  assert.match(subjectWheel, /<MaterialTagBar controller=\{materialTags\} \/>/)
})

test("el visor PDF.js captura y persiste varias regiones por tag", () => {
  const viewer = source("app/practice/viewer/practice-viewer-client.tsx")
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  const pdfJsHtml = source("public/pdfjs/web/viewer.html")
  assert.match(pdfJs, /pdfjs-custom-tag-button/)
  assert.match(pdfJs, /pdfjs-custom-tag-panel/)
  assert.match(pdfJs, /pdfjs-custom-tag-list/)
  assert.match(pdfJs, /viewerRequestMaterialTags/)
  assert.match(pdfJs, /renderMaterialTags/)
  assert.match(pdfJs, /renderMaterialTagSuggestions/)
  assert.match(pdfJs, /viewerUpdateMaterialTag/)
  assert.match(pdfJs, /viewerRequestMaterialTagRegions/)
  assert.match(pdfJs, /viewerSaveMaterialTagRegions/)
  assert.match(pdfJs, /buildPresentationPdf/)
  assert.match(pdfJs, /openPresentationDocument/)
  assert.match(pdfJs, /state\.app\.open\(\{/)
  assert.match(pdfJs, /presentationTagIds/)
  assert.match(pdfJs, /appendCroppedPdfPage/)
  assert.match(pdfJs, /outputDocument\.embedPage/)
  assert.match(pdfJs, /eventBus\.on\("scalechanging", refreshLayers\)/)
  assert.match(pdfJs, /currentScaleValue = "1\.5"/)
  assert.match(pdfJs, /presentationPhase: "idle"/)
  assert.match(pdfJs, /pdfjs-custom-presentation-preparing/)
  assert.match(pdfJsHtml, /presentationTagIds/)
  assert.doesNotMatch(pdfJs, /renderPresentationRegions/)
  assert.doesNotMatch(pdfJs, /pdfjs-custom-presentation-header/)
  assert.doesNotMatch(pdfJs, /pdfjs-custom-presentation-meta/)
  assert.match(viewer, /loadViewerMaterialTagRegions/)
  assert.match(viewer, /saveViewerMaterialTagRegions/)
  assert.match(pdfJs, /activeRegionTagId == null\) closeMaterialTagPanel/)
  assert.match(pdfJs, /viewerRequestMaterialTag/)
  assert.match(viewer, /assignViewerMaterialTag/)
  assert.match(viewer, /viewerMaterialTagResult/)
  assert.match(viewer, /updateViewerMaterialTag/)
  assert.doesNotMatch(viewer, /<MaterialTagPicker/)
  assert.doesNotMatch(pdfJs, /\/api\/tags/)
  assert.doesNotMatch(viewer, /RegionPresentationClient/)
})

test("Escape sale de presentacion sin cerrar el visor PDF.js", () => {
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  const escapeHandler = pdfJs.match(
    /function handleViewerEscape\(event\) \{([\s\S]*?)\n  \}\n\n  function showLoadingOverlay/
  )?.[1]

  assert.ok(escapeHandler, "debe existir el manejador de Escape del visor")
  assert.match(escapeHandler, /event\?\.preventDefault\?\.\(\)/)
  assert.doesNotMatch(escapeHandler, /navigateBackToApp|viewerRequestClose|location\.assign/)
})

test("el visor exporta rangos inclusivos copiando paginas PDF sin rasterizarlas", () => {
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  const css = source("public/pdfjs/web/viewer-custom.css")
  assert.match(pdfJs, /pdfjs-custom-cut-button/)
  assert.match(pdfJs, /handleCutPageClick/)
  assert.match(pdfJs, /handleCutButtonClick/)
  assert.match(pdfJs, /firstPage === pageNumber/)
  assert.doesNotMatch(pdfJs, /Toca la pagina inicial del recorte/)
  assert.doesNotMatch(pdfJs, /Pulsa la tijera para descargar/)
  assert.match(pdfJs, /buildCopiedPageRangePdf/)
  assert.match(pdfJs, /outputDocument\.copyPages/)
  assert.match(pdfJs, /state\.app\.pdfDocument\.saveDocument/)
  assert.doesNotMatch(pdfJs, /buildRasterizedPageRangePdf/)
  assert.doesNotMatch(pdfJs, /canvasToJpegBytes/)
  assert.match(pdfJs, /_paginas-\$\{startPage\}-\$\{endPage\}/)
  assert.match(pdfJs, /URL\.createObjectURL/)
  assert.match(pdfJs, /openPageRangeNameDialog/)
  assert.match(pdfJs, /modalMode = "page-range-download"/)
  assert.match(pdfJs, /replace\(\/\\\.pdf\$\/i, ""\)/)
  assert.match(pdfJs, /normalizePdfFileName\(strippedName\)/)
  assert.doesNotMatch(pdfJs, /pdfjs-custom-cut-start/)
  assert.match(css, /data-cut-boundary="start"/)
  assert.match(css, /data-cut-boundary="end"/)
})

test("PDF.js traduce la seleccion junto al texto y permite editar el prompt", () => {
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  const pdfJsHtml = source("public/pdfjs/web/viewer.html")
  const css = source("public/pdfjs/web/viewer-custom.css")
  const route = source("app/api/pdf-translate/route.ts")
  const interceptor = source("components/local-fetch-interceptor.tsx")
  const proxy = source("proxy.ts")
  assert.match(pdfJsHtml, /translateSelectionButton/)
  assert.doesNotMatch(pdfJsHtml, /id="translateSelectionButton"[^>]*disabled/)
  assert.match(pdfJsHtml, /translatePromptButton/)
  assert.match(pdfJs, /captureViewerTextSelection/)
  assert.match(pdfJs, /pdfjs-custom-translation-popover/)
  assert.match(pdfJs, /TRANSLATION_PROMPT_STORAGE_KEY/)
  assert.match(pdfJs, /prompt\.includes\("\{texto\}"\)/)
  assert.match(pdfJs, /fetch\("\/api\/pdf-translate"/)
  assert.match(pdfJs, /translationMode/)
  assert.match(pdfJs, /state\.translateButton\.disabled = false/)
  assert.match(pdfJs, /if \(state\.translationMode\) void translateSelectedText\(\)/)
  assert.match(css, /pdfjs-custom-translation-popover/)
  assert.match(css, /aria-pressed="true"/)
  assert.match(route, /PDF_TRANSLATION_MODEL/)
  assert.match(route, /temperature: 0\.1/)
  assert.match(interceptor, /url\.pathname === "\/api\/pdf-translate"/)
  assert.match(proxy, /pathname === "\/api\/pdf-translate"[\s\S]*?NextResponse\.next\(\)/)
})

test("sincronizar usa icono compacto en la barra y texto en mas opciones", () => {
  const html = source("public/pdfjs/web/viewer.html")
  const css = source("public/pdfjs/web/viewer-custom.css")
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  assert.match(html, /id="syncButton"[\s\S]*?<svg/)
  assert.match(html, /id="secondarySyncButton"[\s\S]*?<span>Sincronizar<\/span>/)
  assert.match(css, /#syncButton\.pdfjs-custom-sync-button[\s\S]*?min-width: 32px/)
  assert.match(pdfJs, /button\.setAttribute\("aria-label", accessibleLabel\)/)
})

test("contenedores, NLM y regiones tienen contratos persistentes y locales", () => {
  const migration = source("scripts/030-add-material-containers-nlm-and-tag-regions.sql")
  const subjectWheel = source("components/subject-wheel.tsx")
  const tagBar = source("components/material-tag-bar.tsx")
  const interceptor = source("components/local-fetch-interceptor.tsx")
  assert.match(migration, /subject_material_containers/)
  assert.match(migration, /material_tag_regions/)
  assert.match(migration, /'nlm'/)
  assert.match(subjectWheel, /createSubjectMaterialContainer/)
  assert.match(subjectWheel, /event\.key !== "\+"/)
  assert.match(subjectWheel, /buildMaterialRegionPresentationHref/)
  assert.match(tagBar, /event\.key === "\+"/)
  assert.match(tagBar, /if \(!nextInput\.trim\(\)\)/)
  assert.match(tagBar, /closeFloatingSearch\(\)/)
  assert.match(interceptor, /listLocalSubjectMaterialContainers/)
  assert.match(interceptor, /replaceLocalMaterialTagRegions/)
})

test("los contenedores custom se fijan, ordenan y cargan globalmente", () => {
  const migration = source("scripts/031-pin-material-containers.sql")
  const containers = source("lib/material-containers.ts")
  const localData = source("lib/local-workspace-data.ts")
  const interceptor = source("components/local-fetch-interceptor.tsx")
  const subjectWheel = source("components/subject-wheel.tsx")
  assert.match(migration, /is_pinned BOOLEAN NOT NULL DEFAULT FALSE/)
  assert.match(containers, /setSubjectMaterialContainerPinned/)
  assert.match(containers, /moveSubjectMaterialContainer/)
  assert.match(localData, /setLocalSubjectMaterialContainerPinned/)
  assert.match(localData, /moveLocalSubjectMaterialContainer/)
  assert.match(localData, /listLocalPinnedSubjectMaterials/)
  assert.match(interceptor, /scope === "pinned"/)
  assert.match(subjectWheel, /scope: "pinned"/)
  assert.match(subjectWheel, /container\.isPinned \? "text-foreground"/)
  assert.match(subjectWheel, /containerGroupIndex/)
})

test("un tag del objeto materia filtra; su x separada es la que lo quita del PDF", () => {
  const subjectWheel = source("components/subject-wheel.tsx")
  assert.match(subjectWheel, /Ver materiales con #\$\{tag\.name\}/)
  assert.match(subjectWheel, /Quitar #\$\{tag\.name\} de este PDF/)
  assert.match(subjectWheel, /materialTags\.toggleSelectedTag\(tag\.id\)/)
  assert.match(subjectWheel, /materialTags\.unassignTag\(material\.id, tag\.id\)/)
})

test("el visor abre la fuente real sin prevalidarla ni crear rutas inexistentes", () => {
  const viewer = source("app/practice/viewer/practice-viewer-client.tsx")
  const page = source("app/practice/viewer/page.tsx")
  const pdfJs = source("public/pdfjs/web/viewer-custom.js")
  assert.match(viewer, /localWorkspaceMode\s*\?\s*""/)
  assert.match(viewer, /`\/api\/subject-day-materials\/\$\{material\.id\}\/file`/)
  assert.match(viewer, /key=\{viewerIdentity\}/)
  assert.doesNotMatch(viewer, /validateWorkspaceMaterialIdentity|preloadPracticePdf|%PDF-/)
  assert.doesNotMatch(page, /drive_mime_type\s*\|\|.*includes\("pdf"\)/)
  assert.match(pdfJs, /getDirectoryHandle\(segment, \{ create: false \}\)/)
  assert.match(pdfJs, /getFileHandle\(fileName, \{ create: false \}\)/)
  assert.match(pdfJs, /eventBus\.on\("documentloaded", onDocumentLoaded\)/)
  assert.match(pdfJs, /fingerprint: state\.app\?\.pdfDocument\?\.fingerprints/)
})
